### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by cristianvaz** [AOSPK/official_devices#114]
## Device you want to apply for
```
alioth
```

## Device tree sources

```
https://github.com/cristianvaz/device_xiaomi_alioth
https://github.com/cristianvaz/device_xiaomi_sm8250-common
https://github.com/GZR-Kernels/Optimus_Drunk_Alioth
https://github.com/cristianvaz/vendor_xiaomi_sm8250-common
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@cvaz93
```

### GitHub username
```
cristianvaz
```

**Comment by clawside** [comment]
Good morning / afternoon / evening, I hope you are well, I am glad that you are interested in applying for AOSPK, everything seems fine excepting the kernel, because it uses Boeffla WL blocker, so, you must use the kernel common that are in devices org, please make a pull request with all information of what you need. Check PM in Telegram.
